# Generated by Django 4.0.2 on 2022-02-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
    ]
