# Generated by Django 4.0.2 on 2022-02-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_img_city_image_rename_img_country_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='img',
        ),
    ]
