# Generated by Django 4.0.2 on 2022-02-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_image_city_img_rename_image_country_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
