# Generated by Django 4.0.2 on 2022-02-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_extendedusers_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('img', models.TextField(blank=True, max_length=500)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
    ]
