# Generated by Django 4.0.2 on 2022-02-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_post_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=50)),
                ('profile_picture', models.TextField(default='https://i.pinimg.com/736x/cb/45/72/cb4572f19ab7505d552206ed5dfb3739.jpg', max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='city',
            new_name='current_city',
        ),
    ]
