# Generated by Django 4.0.2 on 2022-02-17 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_profile_rename_city_post_current_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedusers',
            name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='current_city',
            new_name='favourite_city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='current_city',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='email', max_length=300, unique=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='ExtendedUsers',
        ),
    ]
