INSERT INTO main_app_country(name, image, continent)
    VALUES
    ("United States","https://www.kindpng.com/picc/m/61-611171_us-flag-shape-of-country-hd-png-download.png","North America");

INSERT INTO main_app_country(name, image, continent)
    VALUES
    ("Brazil","https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/brazil-flag-border-gift-country-pride-identity-fan-funny-gift-ideas.jpg","South America");
INSERT INTO main_app_country(name, image, continent)
    VALUES
    ("Italy","https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/italy-flag-in-country-silhouette-peter-hermes-furian.jpg","Europe");

INSERT INTO main_app_country(name, image, continent)
    VALUES
    ("Japan","https://ih1.redbubble.net/image.903835950.0919/st,small,845x845-pad,1000x1000,f8f8f8.jpg","Asia");

INSERT INTO main_app_country(name, image, continent)
    VALUES
    ("Australia","https://cdn11.bigcommerce.com/s-plfev599h5/images/stencil/1280x1280/products/55544/168933/41MGRRitBpL__83715.1602574540.jpg?c=1","Australia");
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Miami","https://mmimageservice.azurewebsites.net/api/image/office/039","Miami, officially the City of Miami, is a coastal metropolis located in Miami-Dade County in southeastern Florida. With a population of 467,963 as of the 2020 census, it is the 44th-largest city in the United States and the core of the nation's eighth-largest metropolitan area.","United States")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Los Angles,","https://a.cdn-hotels.com/gdcs/production104/d87/607b5514-cc8b-4db2-a40b-8087b6dd9135.jpg","Los Angeles is a sprawling Southern California city and the center of the nation’s film and television industry. Near its iconic Hollywood sign, studios such as Paramount Pictures, Universal and Warner Brothers offer behind-the-scenes tours. On Hollywood Boulevard, TCL Chinese Theatre displays celebrities’ hand- and footprints, the Walk of Fame honors thousands of luminaries and vendors sell maps to stars’ homes","United States")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("New York","https://www.history.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTU3ODc5MDgyNjY5OTc1MjYz/new-york-city.jpg","New York City comprises 5 boroughs sitting where the Hudson River meets the Atlantic Ocean. At its core is Manhattan, a densely populated borough that’s among the world’s major commercial, financial and cultural centers. Its iconic sites include skyscrapers such as the Empire State Building and sprawling Central Park. Broadway theater is staged in neon-lit Times Square.","United States")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Rio de Janiero","https://static1.evcdn.net/images/reduction/1253999_w-1200_h-630_q-70_m-crop.jpg","Rio de Janeiro is a huge seaside city in Brazil, famed for its Copacabana and Ipanema beaches, 38m Christ the Redeemer statue atop Mount Corcovado and for Sugarloaf Mountain, a granite peak with cable cars to its summit. The city is also known for its sprawling favelas (shanty towns). Its raucous Carnaval festival, featuring parade floats, flamboyant costumes and samba dancers, is considered the world’s largest","Brazil")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Brazilla","https://ychef.files.bbci.co.uk/976x549/p0216mjh.jpg","Brasília, inaugurated as Brazil’s capital in 1960, is a planned city distinguished by its white, modern architecture, chiefly designed by Oscar Niemeyer. Laid out in the shape of an airplane, its “fuselage” is the Monumental Axis, 2 wide avenues flanking a massive park. In the “cockpit” is Praça dos Três Poderes, named for the 3 branches of government surrounding it","Brazil")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Sao Paulo","https://assets.tivolihotels.com/image/upload/q_auto,f_auto/media/minor/tivoli/images/destination/saopaulo/thr_top_saopaulo_1920x1000.jpg","São Paulo, Brazil’s vibrant financial center, is among the world's most populous cities, with numerous cultural institutions and a rich architectural tradition. Its iconic buildings range from its neo-Gothic cathedral and the 1929 Martinelli skyscraper to modernist architect Oscar Niemeyer’s curvy Edifício Copan. The colonial-style Pátio do Colégio church marks where Jesuit priests founded the city in 1554.","Brazil")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Rome","https://www.fodors.com/wp-content/uploads/2018/10/HERO_UltimateRome_Hero_shutterstock789412159.jpg","Rome is the capital city of Italy. It is also the capital of the Lazio region, the centre of the Metropolitan City of Rome, and a special comune named Comune di Roma Capitale","Italy")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Florence","https://images.ctfassets.net/i3kf1olze1gn/1HEN72CsnOemYAW33xizob/63cea14198d237d94922830aebf552a8/herr-bohn-EFPLaoX5nuY-unsplash.jpg?q=55&w=640","Florence, capital of Italy’s Tuscany region, is home to many masterpieces of Renaissance art and architecture. One of its most iconic sights is the Duomo, a cathedral with a terracotta-tiled dome engineered by Brunelleschi and a bell tower by Giotto. The Galleria dell'Accademia displays Michelangelo’s “David” sculpture. The Uffizi Gallery exhibits Botticelli’s “The Birth of Venus” and da Vinci’s “Annunciation.”","Italy")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Venice","https://imageio.forbes.com/specials-images/imageserve/609bccd983c8e785ad906ba2/Venice-at-sunny-evening/960x0.jpg?fit=bounds&format=jpg&width=960","Venice, the capital of northern Italy’s Veneto region, is built on more than 100 small islands in a lagoon in the Adriatic Sea. It has no roads, just canals – including the Grand Canal thoroughfare – lined with Renaissance and Gothic palaces. The central square, Piazza San Marco, contains St. Mark’s Basilica, which is tiled with Byzantine mosaics, and the Campanile bell tower offering views of the city’s red roofs.","Italy")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Tokyo","https://i.insider.com/5d26280921a86107bb51bd92?width=700","Tokyo, Japan’s busy capital, mixes the ultramodern and the traditional, from neon-lit skyscrapers to historic temples. The opulent Meiji Shinto Shrine is known for its towering gate and surrounding woods. The Imperial Palace sits amid large public gardens. The city's many museums offer exhibits ranging from classical art (in the Tokyo National Museum) to a reconstructed kabuki theater (in the Edo-Tokyo Museum).","Japan")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Kyoto","https://kyoto-amc.iafor.org/wp-content/uploads/sites/55/2017/01/The-Kyoto-Conference-on-Arts-Media-Culture-7.jpg","Kyoto, once the capital of Japan, is a city on the island of Honshu. It's famous for its numerous classical Buddhist temples, as well as gardens, imperial palaces, Shinto shrines and traditional wooden houses. It’s also known for formal traditions such as kaiseki dining, consisting of multiple courses of precise dishes, and geisha, female entertainers often found in the Gion district.","Japan")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Osaka","https://cdn.cheapoguides.com/wp-content/uploads/sites/3/2019/03/Osaka-castle-cherry-blosson-iStock-512491222.jpg","Osaka is a large port city and commercial center on the Japanese island of Honshu. It's known for its modern architecture, nightlife and hearty street food. The 16th-century shogunate Osaka Castle, which has undergone several restorations, is its main historical landmark. It's surrounded by a moat and park with plum, peach and cherry-blossom trees. Sumiyoshi-taisha is among Japan’s oldest Shinto shrines.","Japan")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Sydney","https://images.squarespace-cdn.com/content/v1/55ee34aae4b0bf70212ada4c/1577545161018-1F9Z9ZZQG9JO2O4WCWQX/keith-zhu-qaNcz43MeY8-unsplash+%281%29.jpg?format=1500w","Sydney, capital of New South Wales and one of Australia's largest cities, is best known for its harbourfront Sydney Opera House, with a distinctive sail-like design. Massive Darling Harbour and the smaller Circular Quay port are hubs of waterside life, with the arched Harbour Bridge and esteemed Royal Botanic Garden nearby. Sydney Tower’s outdoor platform, the Skywalk, offers 360-degree views of the city and suburbs.","Australia")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Brisbane","https://www.planetware.com/wpimages/2021/07/australia-victoria-melbourne-top-attractions-intro-paragraph.jpg","Brisbane, capital of Queensland, is a large city on the Brisbane River. Clustered in its South Bank cultural precinct are the Queensland Museum and Sciencentre, with noted interactive exhibitions. Another South Bank cultural institution is Queensland Gallery of Modern Art, among Australia's major contemporary art museums. Looming over the city is Mt. Coot-tha, site of Brisbane Botanic Gardens","Australia")
INSERT INTO main_app_city(name, image, description, country)
    VALUES("Melbourne","https://www.planetware.com/wpimages/2021/07/australia-victoria-melbourne-top-attractions-intro-paragraph.jpg","Melbourne is the coastal capital of the southeastern Australian state of Victoria. At the city's centre is the modern Federation Square development, with plazas, bars, and restaurants by the Yarra River. In the Southbank area, the Melbourne Arts Precinct is the site of Arts Centre Melbourne – a performing arts complex – and the National Gallery of Victoria, with Australian and indigenous art","Australia")